version: '3'
services:
  react-app:
    build: .
    networks:
      - app-network
    volumes:
      - ./react-app:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: npm run dev

networks:
  app-network:
    driver: bridge
