version: '3'
services:
  react-app:
    image: node:18
    volumes:
      - ./react-app:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm create vite@latest . -- --template react && npm install && npm run dev"